version: '3.8'

services:
  mongodb1:
    hostname: mongodb1
    container_name: mongodb1
    image: mongo:latest
    volumes:
      - ./mongodb1-data:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
      - ./mongo/replica.key:/data/replica.key
    ports:
      - 27012:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example@123
    networks:
      - mongo-network
    links:
      - mongodb2
      - mongodb3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  
  mongodb2:
    container_name: mongodb2
    hostname: mongodb2
    image: mongo:latest
    volumes:
      - ./mongodb2-data:/data/db
      - ./mongo/replica.key:/data/replica.key
    ports:
      - 27013:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example@123
    networks:
      - mongo-network
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongodb3:
    container_name: mongodb3
    hostname: mongodb3
    image: mongo:latest
    volumes:
      - ./mongodb3-data:/data/db
      - ./mongo/replica.key:/data/replica.key
    ports:
      - 27014:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example@123
    networks:
      - mongo-network
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongo-network:
    driver: overlay